function aiTurn(){if(!state||state.gameOver)return;state.aiThinking=true;render();updateUndoBtn();const c=AI_CONFIG[settings.difficulty],[lo,hi]=c.thinkTime;setTimeout(()=>{if(!state||state.gameOver){return}const m=aiFindBestMove();if(m)aiExecute(m);else{state.aiThinking=false;skipTurn()}},lo+Math.random()*(hi-lo))}
function aiFindBestMove(){const c=AI_CONFIG[settings.difficulty],mine=activeDice(state.opponentDice),theirs=activeDice(state.youDice);if(!mine.length||!theirs.length)return null;const all=[...aiStr(mine,theirs),...aiMnd(mine,theirs,c.maxOperators)];if(!all.length)return null;all.forEach(m=>m.score=aiScore(m,mine,theirs,c));all.sort((a,b)=>b.score-a.score);if(Math.random()<c.optimalChance){const top=all.filter(m=>m.score>=all[0].score*0.9);return top[Math.floor(Math.random()*top.length)]}return all[Math.floor(Math.random()*all.length)]}
function aiStr(mine,theirs){const moves=[],isL=theirs.length===1,isF=state.firstPlayer===2;mine.forEach(my=>{theirs.forEach(t=>{if((isL&&isF)?my.value>t.value:my.value>=t.value)moves.push({type:'strength',dice:[my],target:t,expression:[{type:'die',id:my.id,value:my.value}]})})});return moves}
function aiMnd(mine,theirs,mx){const moves=[],ops=['+','-','*','/'];for(let n=2;n<=Math.min(mine.length,mx+1);n++){_comb(mine,n).forEach(combo=>{_opComb(ops,n-1).forEach(opSet=>{(n<=3?_perm(combo):[combo]).forEach(perm=>{const r=_evalC(perm,opSet);if(r!==null&&Number.isInteger(r)){const t=theirs.find(d=>d.value===r);if(t){const expr=[];perm.forEach((d,i)=>{expr.push({type:'die',id:d.id,value:d.value});if(i<opSet.length)expr.push({type:'op',value:opSet[i]})});moves.push({type:'mind',dice:perm,target:t,expression:expr})}}})})})};return moves}
function _evalC(d,ops){try{let s=String(d[0].value);for(let i=0;i<ops.length;i++)s+=ops[i]+d[i+1].value;const r=Function('"use strict";return('+s+')')();return Number.isFinite(r)?r:null}catch{return null}}
function aiScore(m,mine,theirs,c){let s=0;if(c.prioritizeHigh)s+=m.target.sides*10;if(m.type==='mind'){s+=(20-m.dice.reduce((a,d)=>a+d.value,0)/m.dice.length)*2;s+=m.dice.length*5}if(m.type==='strength')s+=(m.target.value/m.dice[0].value)*20;if(c.defensive){const rem=mine.filter(d=>!m.dice.includes(d)),ro=theirs.filter(d=>d.id!==m.target.id);if(rem.length&&ro.length&&rem.some(d=>ro.some(o=>d.value>=o.value)))s+=15}return s}
function aiExecute(move){if(!state||state.gameOver)return;state.aiThinking=false;state.attackType=move.type;state.selectedDice=move.dice.map(d=>d.id);state.targetDie=move.target.id;state.expression=move.expression;document.getElementById('btnStrength').classList.toggle('active',move.type==='strength');document.getElementById('btnMind').classList.toggle('active',move.type==='mind');document.getElementById('exprBuilder').hidden=move.type!=='mind';document.getElementById('targetValue').textContent=move.target.value;refreshExpression();render();setTimeout(()=>{if(!state||state.gameOver)return;executeAttack()},600)}
function _comb(a,s){if(s===1)return a.map(x=>[x]);const r=[];a.forEach((item,i)=>{_comb(a.slice(i+1),s-1).forEach(c=>r.push([item,...c]))});return r}
function _perm(a){if(a.length<=1)return[a];const r=[];a.forEach((item,i)=>{const rest=[...a.slice(0,i),...a.slice(i+1)];_perm(rest).forEach(p=>r.push([item,...p]))});return r}
function _opComb(ops,len){if(!len)return[[]];if(len===1)return ops.map(o=>[o]);const r=[];_opComb(ops,len-1).forEach(sub=>{ops.forEach(o=>r.push([o,...sub]))});return r}